services:
  - type: web
    name: zoo_arcadia
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: MONGODB_URI
        value: your_mongodb_atlas_uri_here

    # Facultatif : santé du service
    healthCheckPath: /

   
