services:
  - type: web
    name: zoo_arcadia
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    name: zoo-arcadia
    runtime: php
    # QbuildCommand: chmod +x build.sh && ./build.sh
    startCommand: php -S 0.0.0.0:$PORT -t public



    envVars:
      - key: MONGODB_URI
        value: your_mongodb_atlas_uri_here

    # Facultatif : santé du service
    healthCheckPath: /
