version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
    environment:
      # Tu peux aussi définir ici les variables d'environnement si tu veux
      # Ex: APP_ENV=production
    restart: unless-stopped
