name: PHP Unit Tests

on:
  push:
    branches:
      - main
      - test-unit
  pull_request:
    branches:
      - main
      - test-unit

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1 Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2 Installer PHP 8.2 avec les extensions de base
      - name: Setup PHP with basic extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          coverage: none

      # 3 Installer la version exacte de l'extension MongoDB
      - name: Install exact MongoDB extension version
        run: |
          sudo phpdismod mongodb || true
          sudo pecl install -f mongodb-1.20.0
          echo "extension=mongodb.so" >> $GITHUB_ENV
          echo "extension=mongodb.so" | sudo tee /etc/php/8.2/cli/conf.d/20-mongodb.in

      # 4 Installer les dépendances Composer sans se bloquer sur le lock file
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --ignore-platform-reqs || true

      # 5 Installer PHPUnit directement sur le runner
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit:^10.0 --no-interaction --no-progress --ignore-platform-reqs

      # 6 Lancer les tests PHPUnit
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml