
name: PHP Unit Tests

on:
  push:
    branches:
      - main
      - test-unit
  pull_request:
    branches:
      - main
      - test-unit

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP with basic extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          coverage: none

      - name: Install exact MongoDB extension version
        run: |
          sudo pecl uninstall mongodb || true
          sudo pecl install mongodb-1.20.0
          echo "extension=mongodb.so" >> $GITHUB_ENV

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --ignore-platform-req=ext-mongodb

      - name: In
