
name: Run PHPUnit tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère ton code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installe PHP (ici 8.2, adapte si besoin)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      # 3. Installe les dépendances Composer
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      # 4. Lance PHPUnit
      - name: Run tests
        run: vendor/bin/phpunit --testdox
